## 异步编程

### event loop 运行过程

event loop 结构

- call stack

  存放需要执行的函数 

- call queue

  - 存放宏任务执行完毕的回调函数

    由于执行宏任务需要一定时间，当执行完毕后，会将宏任务的回调函数放入到call queue 中，等待被执行
  - 存放微任务函数

- web api 

  - 存放 setTimeout setInterval 函数
  - 存放请求任务

- event loop

  当 call stack 为空，启动轮训，尝试将 callback queue 的函数移动到 callback stack

### js 是单线程，为什么浏览器可以执行异步任务？

- js 引擎线程发现需要远程请求数据，并且提前注册回调函数 successCb与远程数据response

  ```
  axios({
  	url: "jfdksal",
  	data:"jfkdlas",
  	successCb: (response)=>{}
  })
  ```

- js 引擎线程将请求任务交给HTTP请求线程

- HTTP请求线程完成请求任务，将远程数据放到回调函数的参数response，并且让js引擎线程执行回调函数

### 宏任务与微任务不同点

- 宏任务需要非js引擎线程支持；微任务只需要js 引擎线程支持
- 宏任务可能有多个（定时器线程、请求线程等）；微任务只有一个线程

## promise应用

- 手写promise 
- 中断 promise
- xxx



## 异步代码执行顺序问题

### promise 连续 then catch 代码执行问题

- 连续then，then 应该执行第一个还是第二个函数的规则：

  - 第一个 then 执行 resolve回调函数 or reject回调函数 ？取决于在生成promise，执行的是 resolve 还是 reject 函数

  - 第二个then执行 resolve 回调函数 or reject回调函数？~~取决于第一个 then 的 resolve回调函数 or reject回调函数是否抛出错误~~取决于最后执行的回调函数是否抛出错误

- 题目

  ```javascript
  function axios(url){
    return new Promise((resolve, reject)=>{
      let math = Math.random()
      resolve(math)
    })
  }
  
  axios().then((successData)=>{
    console.log("successData111", successData)
    throw new Error("fdfdfd")
  }, (errorData)=>{
    console.log("errorData111", errorData)
  })
  ```

  ```javascript
  function axios(url){
    return new Promise((resolve, reject)=>{
      let math = Math.random()
      resolve(math)
    })
  }
  axios().then((successData)=>{
    console.log("successData222", successData)
    throw new Error("fdfdfd111")
  }).catch((errorData)=>{
    console.log("errorData catch", errorData)
  })
  ```

  ```javascript
  function axios(url){
    return new Promise((resolve, reject)=>{
      let math = Math.random()
      resolve(math)
    })
  }
  axios().then((successData)=>{
    console.log('第一个then successData', successData)
    throw new Error("fdafdsfdsfdsfdsa") // 核心
  }, (errorData)=>{
    console.log('第一个then errorData', errorData)
  }).then((successData)=>{
    console.log("第二个then successData", successData)
  }, (errorData)=>{
    console.log("第二个then errorData", errorData)
  })
  ```

  ```javascript
  function axios(url){
    return new Promise((resolve, reject)=>{
      let math = Math.random()
      resolve(math)
  //			reject(math)
    })
  }
  axios().then((successData)=>{
    console.log('第一个then successData', successData)
  	throw new Error("fdafdsfdsfdsfdsa") // 核心
  }).catch((errorData)=>{
    console.log('第一个then errorData', errorData)
  }).then((successData)=>{
    console.log("第二个then successData", successData)
  }, (errorData)=>{
    console.log("第二个then errorData", errorData)
  })
  
  ```
  
  ```
  Promise.resolve().then(()=>{
  	console.log(1)
  }).catch(()=>{
  	console.log(2)
  }).then(()=>{
  	console.log(3)
  }) 
  ```
  
  ```
  Promise.resolve().then(()=>{
  	console.log(1)
  	throw new Error("error1")
  }).catch(()=>{
  	console.log(2)
  }).then(()=>{
  	console.log(3)
  })
  ```
  
  ```
  Promise.resolve().then(()=>{
  	console.log(1)
  	throw new Error("error1")
  }).catch(()=>{
  	console.log(2)
  }).catch(()=>{
  	console.log(3)
  })
  ```
  

### setInterval 和 setTimeout  对同步代码的影响

- 异步代码不影响同步代码
- 如果同步任务没有做完，永远不会做异步任务

```javascript
// 结论1：异步代码不影响同步代码
var flag = false

// setInterval 换成 setTimeout 结果是一样的
setInterval(function(){
  flag = true;
}, 1000)
while(flag){
   console.log('running')//
}
// 结果：永远不会打印 running
```

```javascript
// 结论2：如果同步任务没有做完，永远不会做异步任务
let num1 = true
let num2 = 100
setInterval(() => {
  console.log(num2)
}, 1000)

// 由于 num1 是 true ，所以无限打印 log，并且由于是无限操作，同步任务一直都没有做完
// 因此根本不会执行异步任务（打印 num2 = 100）
while (num1) {
  console.log('loop')
}
```



### 纯微任务 async await 执行结果

- `a().then(fn1)` 

  同步执行 a 函数，并且将 fn1 放入到微任务队列，先不执行 fn1

- `async1()` vs `await async1()`

  - 共同点1：`async1`函数本身是同步执行

  - 不同点1：async1 后面的代码执行时机不同

    - `async1()`表示后面的代码是**依然**同步执行
    - `await async1()`表示先执行 async1 代码，然后再将后面的代码放到微任务中
  
    ```javascript
    async function async1(){
    	console.log(1) 
    	await async2()
    	console.log(2)
    }
    async function async2(){
    	console.log(3) 
    }
    // 核心：不加 await 结果是 1 => 3 => 4 => 2；加 await 结果是 1 => 3 => 2 => 4
    // 主要是 2 和 4 的顺序
    async1()
    console.log(4)
    
    ```
  
 - 连续调用 then 

   把第二个 then 放入到微任务最后一个

   【新知识】：调用完微任务 callback3 后，发现有微任务 callback4 ，则把 callback 4 放入微任务最后一个
   
   ```javascript
   Promise.resolve()
     .then(function callback3() {
       console.log("promise1");
     })
     .then(function callback4() {
       console.log("promise2");
     });
   Promise.resolve().then(function callback5() {
     console.log("promise3");
   });
   // 结果：promise1 => promise3 => promise2
   // 微任务队列变化
   // callback3 => callback5
   // ~callback3~ => callback5 => callback4 核心：执行完 callback3 后，发现有 callback4 微任务，因此把 callback4 放入微任务队列最后
   // ~callback3~ => ~callback5~ => callback4
   // ~callback3~ => ~callback5~ => ~callback4~
   ```

```javascript
async function promise1() {
  console.log('promise 1-1')
  await promise2(); // 【新知识】promise2 函数内部是同步执行；后面的所有内容作为 then 的内容执行
  console.log('promise 1-2')
  await promise3();
  console.log('promise 1-3')
}
async function promise2() {
  console.log('promise2');
}
async function promise3() {
  console.log('promise3');
}
promise1(); // 【新知识】如果 async 函数在调用的时候没有 await ，那么后面的内容是同步的
new Promise((resolve) => {
  console.log('promise4');
  resolve()
}).then(() => {
  console.log('100');
})

// 结果
// promise 1-1 => promise2 => promise4 => promise 1-2 => promise3 => 100 => promise 1-3
```

### 微任务 + 宏任务执行结果

- 在执行宏任务之前，必须保证没有微任务

```javascript
setTimeout(function callback5() {
  console.log('timeout1');
  Promise.resolve().then(function callback6() {
    console.log('tttttt')
  })
}, 0);

console.log('start');

Promise.resolve().then(function callback1() {
  console.log('promise1');

  Promise.resolve().then(function callback2() {
    console.log('promise2');
    setTimeout(function callback8() {
      console.log('ppppp')
      Promise.resolve().then(function callback7() {
        console.log('aaaa')
      })
    });
  });

  setTimeout(function callback3() {
    console.log('fffff')
    Promise.resolve().then(function callback4() {
      console.log('promise3');
    });

    console.log('timeout2')
  }, 0);

});

console.log('done');
```

```javascript
console.log("script start");

setTimeout(function callback1() {
  console.log("setTimeout---0");
}, 0);

setTimeout(function callback2() {
  console.log("setTimeout---200");
  setTimeout(function callback11() {
    console.log("inner-setTimeout---0");
  });
  Promise.resolve().then(function callback12() {
    console.log("promise5");
  });
}, 200);

Promise.resolve()
  .then(function callback3() {
    console.log("promise1");
  })
  .then(function callback4() {
    console.log("promise2");//【新知识点】：搜索 「连续调用 then」
  });
Promise.resolve().then(function callback5() {
  console.log("promise3");
});
console.log("script end");
// 结果： script start => script end => promise1 => promise3=> promise2 => setTimeout---0 => setTimeout---200 => promise5 => inner-setTimeout---0
// 微任务 ~callback3~ => ~callback5~ => ~callback4~ => ~callback12~
// 宏任务 ~callback1~ => ~callback2~ => ~callback11~
```

### 不正常使用await async

将非 promise 值包装成 fullFilled 状态的 `Promise.resolve(这里放非 promise 值)`

```javascript
async function test() {
  const num = await 123; // 等价于 const num = await Promise.resolve(123) 
  console.log(num)
}
test()
```

```javascript
async function test() {
  const num = await setTimeout(() => {
    console.log(1)
  }, 1000);
  // 等价于
  /*
  const num = await Promise.resolve(setTimeout(() => {
    console.log(1)
  }, 1000))
  */
  console.log(num);
}
test()
```



